version: "3.1"
services:

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - vt_mongo_data:/data/db
    logging:
      driver: none

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - vt_redis_data:/data
    logging:
      driver: none

  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: virtool
      POSTGRES_PASSWORD: virtool
    volumes:
      - vt_postgres_data:/var/lib/postgresql/data
    logging:
      driver: none

  backend:
    image: virtool/virtool:5.11.5
    expose:
      - "9950"
    ports:
      - "9950:9950"
    volumes:
      - vt_backend_data:/data
    environment:
      VT_DEV: "true"
      VT_SERVER_HOST: "0.0.0.0"
      VT_REDIS_CONNECTION_STRING: "redis://redis:6379"
      VT_POSTGRES_CONNECTION_STRING: "postgresql+asyncpg://virtool:virtool@postgres/virtool"
      VT_DB_CONNECTION_STRING: "mongodb://mongo:27017"


volumes:
  vt_mongo_data:
  vt_redis_data:
  vt_postgres_data:
  vt_pgadmin4_data:
  vt_backend_data:
