/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/js/**/*.{html,js,jsx,ts,tsx}"],
    theme: {
        colors: {
            black: "#000000",
            blue: "#0B7FE5",
            blueDark: "#0862C4",
            blueDarkest: "#033384",
            blueLight: "#6AC4F7",
            blueLightest: "#CDF1FD",
            green: "#1DAD57",
            greenDark: "#159455",
            greenDarkest: "#096449",
            greenLight: "#73E68A",
            greenLightest: "#D1FAD1",
            grey: "#A0AEC0",
            greyDark: "#718096",
            greyDarkest: "#4A5568",
            greyLight: "#CBD5E0",
            greyLightest: "#EDF2F7",
            greyHover: "#F7FAFC",
            orange: "#F7A000",
            orangeLight: "#FCD265",
            orangeLightest: "#FEF4CB",
            orangeDark: "#D48100",
            orangeDarkest: "#B16600",
            primary: "#3C8786",
            primaryDark: "#2B6E74",
            primaryDarkest: "#1E5661",
            primaryLight: "#6AB7AF",
            primaryLightest: "#E8F5F5",
            purple: "#9F7AEA",
            purpleDark: "#805AD5",
            purpleDarkest: "#553C9A",
            purpleLight: "#D6BCFA",
            purpleLightest: "#FAF5FF",
            red: "#E0282E",
            redDark: "#C01D30",
            redDarkest: "#A11431",
            redLight: "#F58E7C",
            redLightest: "#FDE1D3",
            white: "#fff",
            yellow: "#FFE030",
            yellowLight: "#FFF082",
            yellowLightest: "#FFFBD5",
            yellowDark: "#DBBC23",
            yellowDarkest: "#B79A18",
        },
        extend: {},
    },
    plugins: [],
};
