const crypto = require("crypto");

const fontAwesomeURL = "https://use.fontawesome.com";
const defaultSrc = "default-src 'self'";
const imgSrc = "img-src 'self' data:";
const fontSrc = `font-src 'self' https://fonts.gstatic.com ${fontAwesomeURL}`;
const connectSrc = "connect-src 'self' sentry.io";

const generateCSPScriptSrc = (nonce) => {
  return `script-src 'self' 'nonce-${nonce}' ${fontAwesomeURL}`;
};

const generateCSPStyleSrc = (nonce) => {
  return `style-src 'self' 'nonce-${nonce}' https://fonts.googleapis.com ${fontAwesomeURL}`;
};

/**
 * Applies CSP header to response object
 *
 * @func
 * @param req {object} the request object generated by express
 * @param res {object} the response object generated by express
 * @param next {function} passes control to next middleware
 * @returns {N/A}
 */
exports.applyCSPHeader = (req, res, next) => {
  const nonce = crypto.randomBytes(32).toString("base64");
  res.locals.nonce = nonce;

  const csp = [
    connectSrc,
    defaultSrc,
    fontSrc,
    imgSrc,
    generateCSPScriptSrc(nonce),
    generateCSPStyleSrc(nonce),
  ];

  res.append("Content-Security-Policy", csp.join("; "));

  next();
};
